# Generated by Django 4.0.6 on 2022-08-23 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=5000)),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('pname', models.CharField(max_length=50)),
                ('pdescription', models.TextField(max_length=2000)),
                ('pprice', models.FloatField()),
                ('pcategory', models.CharField(max_length=50)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommercepp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=5000)),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.JSONField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommercepp.customer')),
            ],
        ),
    ]
