# Generated by Django 4.0.6 on 2022-08-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0002_alter_cart_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="pid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecommercepp.product"
            ),
        ),
    ]
