# Generated by Django 4.0.6 on 2022-08-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0005_delete_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sellerid",
        ),
    ]
