# Generated by Django 4.0.6 on 2022-08-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0008_rename_sellerid_seller_sellername"),
    ]

    operations = [
        migrations.DeleteModel(
            name="seller",
        ),
    ]
