# Generated by Django 4.0.6 on 2022-08-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0010_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="sellername",
            new_name="sellerid",
        ),
    ]
