# Generated by Django 4.0.6 on 2022-08-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0012_alter_product_sellerid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="sellerid",
            new_name="authid",
        ),
    ]
