# Generated by Django 4.0.6 on 2022-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0013_rename_sellerid_seller_authid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pcategory",
            field=models.CharField(max_length=50),
        ),
    ]
