# Generated by Django 4.0.6 on 2022-08-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0015_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecommercepp.customer"
            ),
        ),
    ]
