# Generated by Django 4.0.6 on 2022-08-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0016_alter_cart_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="userid",
            new_name="custid",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ptotal",
        ),
    ]
