# Generated by Django 4.0.6 on 2022-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0017_rename_userid_cart_custid_remove_cart_ptotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="pid",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pname",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pprice",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pqty",
        ),
        migrations.AddField(
            model_name="cart",
            name="cartitem",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
