# Generated by Django 4.0.6 on 2022-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0021_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
