# Generated by Django 4.0.6 on 2022-08-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0025_alter_seller_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="phone",
        ),
    ]
