# Generated by Django 4.0.6 on 2022-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0026_remove_seller_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="phone",
            field=models.CharField(default="0", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
