# Generated by Django 4.0.6 on 2022-08-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0027_seller_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="authid",
            new_name="auth_id",
        ),
        migrations.RenameField(
            model_name="seller",
            old_name="authid",
            new_name="auth_id",
        ),
    ]
