# Generated by Django 4.0.6 on 2022-08-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommercepp", "0029_rename_sellerid_product_seller_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="custid",
            new_name="cust_id",
        ),
    ]
